name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run standard
        run: bundle exec rake rubocop
      - name: Run specs
        run: bundle exec rake spec
      - name: Run Coverage
        uses: joshmfrankel/simplecov-check-action@main
        with:
          minimum_suite_coverage: 95
          github_token: ${{ secrets.GITHUB_TOKEN }}
